-- 006 (substituída): a versão anterior criava o papel `oms_login` (BYPASSRLS)
-- e funções SECURITY DEFINER do superusuário para o login. Só rodava como
-- superusuário; no banco da VPS (usuário comum, dono do banco) a migração
-- falhava e o login ficava sem a função `find_login` ("Erro interno").
--
-- O login agora acha a lojamestre pelo slug (`tenants` não tem RLS) e lê o
-- usuário no contexto dela (app.tenant_id), sem papel especial. A 007 remove
-- as funções onde a versão anterior chegou a rodar.
